services:
  - type: web
    name: test-auto1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn geopark_data_pipeline:app
    plan: free
    envVars:
      - key: RENDER
        value: true
      - key: MONGODB_URI
        value: mongodb+srv://lgallego:LauGalle3101@clusteria.at4taak.mongodb.net/market_data?retryWrites=true&w=majority&appName=ClusterIA
      - key: MONGODB_DB
        value: market_data
      - key: MONGODB_COLLECTION
        value: geopark_daily
      - key: ALPHA_VANTAGE_API_KEY
        value: BCCMWJX0WL7IQYVE
      - key: SCHEDULE_TIME
        value: "18:00"
      - key: PORT
        value: "10000" 